version: "3.5"

services:

  # This is a persistent minio instance that can be used
  # as an s3-substitute outside of the test environment.
  s3_local:
    networks:
      - ehri-frontend-minio_default
    image: quay.io/minio/minio:RELEASE.2024-02-26T09-33-48Z
    ports:
      - 9100:9000
      - 9101:9001
    environment:
      MINIO_ROOT_USER: docview
      MINIO_ROOT_PASSWORD: changeme
    command: server --console-address ":9001" /data
    restart: always
    volumes:
      - "./miniodata/data:/data"

# Use a non-default network so it doesn't collide with the
# default (test) network
networks:
  ehri-frontend-minio_default:
    name: minio_default
