<script lang="ts">

import AccessPointType from "./components/_access-point-type";
import AccessPointEditorApi from "./api";

// These variables are expected to be in the window global scope
// and are generated by server-side data.
const CONFIG = (window as any).CONFIG as ConfigType;
const SERVICE = (window as any).SERVICE as any;

export default {
  components: {AccessPointType},
  data() {
    return {
      api: new AccessPointEditorApi(SERVICE, CONFIG),
      config: CONFIG,
      loading: true,
      types: []
    }
  },
  methods: {
    reload: function () {
      this.loading = true;
      this.api.getAccessPoints(CONFIG.id, CONFIG.did).then(types => {
        this.loading = false;
        this.types = types
      });
    }
  },
  created: function () {
    this.reload();
  },
}
</script>

<template>
  <div id="access-point-editor" class="ap-editor">
    <span v-if="loading">Loading...</span>
    <ul class="ap-editor-types">
      <access-point-type
          v-for="type in types"
          v-bind:key="type.type"
          v-bind:type="type.type"
          v-bind:access-points="type.data"
          v-bind:api="api"
          v-bind:config="config"
          v-on:deleted="reload"
          v-on:added="reload"
        />
    </ul>
  </div>
</template>
