
CREATE TABLE feedback (
  id CHAR(10) NOT NULL PRIMARY KEY,
  user_id VARCHAR(50) DEFAULT NULL,
  name VARCHAR (255) DEFAULT NULL,
  email VARCHAR (255) DEFAULT NULL,
  text MEDIUMTEXT,
  type VARCHAR (10) DEFAULT NULL,
  copy BOOLEAN DEFAULT FALSE,
  context TEXT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP NULL ,
  mode VARCHAR(10) NOT NULL
) CHARACTER SET utf8 COLLATE utf8_general_ci;

