BEGIN TRANSACTION;

ALTER TABLE users
    ALTER COLUMN verified SET NOT NULL,
    ALTER COLUMN verified SET DEFAULT FALSE,
    ALTER COLUMN verified TYPE BOOLEAN USING CASE WHEN verified = 1 THEN TRUE WHEN verified = 0 THEN FALSE ELSE NULL END,

    ALTER COLUMN staff SET NOT NULL,
    ALTER COLUMN staff SET DEFAULT FALSE,
    ALTER COLUMN staff TYPE BOOLEAN USING CASE WHEN staff = 1 THEN TRUE WHEN staff = 0 THEN FALSE ELSE NULL END,

    ALTER COLUMN active SET NOT NULL,
    ALTER COLUMN active SET DEFAULT TRUE,
    ALTER COLUMN active TYPE BOOLEAN USING CASE WHEN active = 1 THEN TRUE WHEN active = 0 THEN FALSE ELSE NULL END,

    ALTER COLUMN allow_messaging SET NOT NULL,
    ALTER COLUMN allow_messaging SET DEFAULT TRUE,
    ALTER COLUMN allow_messaging TYPE BOOLEAN USING CASE WHEN allow_messaging = 1 THEN TRUE WHEN allow_messaging = 0 THEN FALSE ELSE NULL END,

    ALTER COLUMN is_legacy SET NOT NULL,
    ALTER COLUMN is_legacy SET DEFAULT FALSE,
    ALTER COLUMN is_legacy TYPE BOOLEAN USING CASE WHEN is_legacy = 1 THEN TRUE WHEN is_legacy = 0 THEN FALSE ELSE NULL END;

ALTER TABLE token
    ALTER COLUMN is_sign_up SET NOT NULL,
    ALTER COLUMN is_sign_up SET DEFAULT FALSE,
    ALTER COLUMN is_sign_up TYPE BOOLEAN USING CASE WHEN is_sign_up = 1 THEN TRUE WHEN is_sign_up = 0 THEN FALSE ELSE NULL END;

ALTER TABLE research_guide
    ALTER COLUMN active SET NOT NULL,
    ALTER COLUMN active SET DEFAULT TRUE,
    ALTER COLUMN active TYPE BOOLEAN USING CASE WHEN active = 1 THEN TRUE WHEN active = 0 THEN FALSE ELSE NULL END;

ALTER TABLE feedback
    ALTER COLUMN copy SET DEFAULT FALSE,
    ALTER COLUMN copy TYPE BOOLEAN USING CASE WHEN copy = 1 THEN TRUE WHEN copy = 0 THEN FALSE ELSE NULL END;

ALTER TABLE cypher_queries
    ALTER COLUMN public SET DEFAULT FALSE,
    ALTER COLUMN public TYPE BOOLEAN USING CASE WHEN public = 1 THEN TRUE WHEN public = 0 THEN FALSE ELSE NULL END;

COMMIT;
