#! /bin/sh

# description: Docview Start Stop Restart
# chkconfig: 234 20 80
#JAVA_HOME=/usr/java/jdk1.7.0_05
#JAVA_HOME=/usr/lib/jvm/jre-1.6.0-sun.x86_64
JAVA_HOME=/usr/lib/jvm/jre-1.7.0-oracle.x86_64
export JAVA_HOME
PATH=$JAVA_HOME/bin:$PATH
export PATH

export USER=docview

APP="docview"
APP_PATH="/opt/webapps/$APP"
CONF=$APP_PATH/conf/prod.conf

start() {
	cd $APP_PATH
	su $USER -c "$APP_PATH/target/start -Dplay.evolutions.default.autoApply=false -Dhttp.port=9000 -Dconfig.file=$CONF &"
}

stop() {
kill `cat $APP_PATH/RUNNING_PID`
}

case "$1" in
start)
echo "Starting $APP"
start
echo "$APP started."
;;
stop)
echo "Stopping $APP"
stop
echo "$APP stopped."
;;
restart)
echo  "Restarting $APP."
stop
sleep 2
start
echo "$APP restarted."
;;
*)
N=/etc/init.d/$APP
echo "Usage: $N {start|stop|restart}" >&2
exit 1
;;
esac

exit 0
