<script lang="ts">

import ManagerDatasets from './components/_manager-datasets';
import MixinUtil from './components/_mixin-util';
import {DatasetManagerApi} from "./api";

import {ConfigType} from "./types";

if (typeof window !== 'undefined') {
  // Prevent default drag/drop action...
  window.addEventListener("dragover", e => e.preventDefault(), false);
  window.addEventListener("drop", e => e.preventDefault(), false);
}

// These variables are expected to be in the window global scope
// and are generated by server-side data.
const CONFIG = (window as any).CONFIG as ConfigType;
const SERVICE = (window as any).SERVICE as any;

export default {
  components: {ManagerDatasets},
  mixins: [MixinUtil],
  data: function() {
    return {
      config: CONFIG,
      api: new DatasetManagerApi(SERVICE, CONFIG.repoId),
      tab: 'input',
    }
  },
}
</script>

<template>
  <div id="app-container">
    <manager-datasets
        v-bind:config="config"
        v-bind:init-tab="tab"
        v-bind:api="api" />
  </div>
</template>
