package models.json

import models._
import play.api.libs.json.Json

/**
 * User: michaelb
 * 
 * Json formats for client. These are auto-generated by the framework
 * macro and simply match the case classes.
 */
package object client {

//  implicit val accessPointFormat = Json.writes[AccessPointF]
//  implicit val addressFormat = Json.writes[AddressF]
//  implicit val annotationFormat = Json.writes[AnnotationF]
//  implicit val authoritativeSetFormat = Json.writes[AuthoritativeSetF]
//  implicit val conceptFormat = Json.writes[ConceptF]
//  implicit val conceptDescriptionFormat = Json.writes[ConceptDescriptionF]
//  implicit val countryFormat = Json.writes[CountryF]
//  implicit val datePeriodFormat = Json.writes[DatePeriodF]
//  implicit val documentaryUnitFormat = Json.writes[DocumentaryUnitF]
//  implicit val groupFormat = Json.writes[GroupF]
//  implicit val historicalAgentFormat = Json.writes[HistoricalAgentF]
//
//  import RepositoryDescriptionF.{Details => RDDetails, Control => RDControl}
//  implicit val isaarFormat = Json.writes[HistoricalAgentDescriptionF]
//  implicit val isaarDetailsFormat = Json.writes[HistoricalAgentDescriptionF.Details]
//  implicit val isaarControlFormat = Json.writes[HistoricalAgentDescriptionF.Control]
//
//  implicit val isadGFormat = Json.writes[DocumentaryUnitDescriptionF]
//  implicit val isadGContextFormat = Json.writes[DocumentaryUnitDescriptionF.Context]
//  implicit val isadGContentFormat = Json.writes[DocumentaryUnitDescriptionF.Content]
//  implicit val isadGConditionsFormat = Json.writes[DocumentaryUnitDescriptionF.Conditions]
//  implicit val isadGMaterialsFormat = Json.writes[DocumentaryUnitDescriptionF.Materials]
//  implicit val isadGControlFormat = Json.writes[DocumentaryUnitDescriptionF.Control]
//
//  implicit val isdiahFormat = Json.writes[RepositoryDescriptionF]
//  implicit val isdiahDetailsFormat = Json.writes[RepositoryDescriptionF.Details]
//  implicit val isdiahAccessFormat = Json.writes[RepositoryDescriptionF.Access]
//  implicit val isdiahServicesFormat = Json.writes[RepositoryDescriptionF.Services]
//  implicit val isdiahControlFormat = Json.writes[RepositoryDescriptionF.Control]
//
//  implicit val linkFormat = Json.writes[LinkF]
//  implicit val repositoryFormat = Json.writes[RepositoryF]
//  implicit val userProfileFormat = Json.writes[UserProfileF]
//  implicit val vocabularyFormat = Json.writes[VocabularyF]

}
